

## **Lab : Data Manipulation and basic concept of pandas lib**

Dataset:  https://gist.githubusercontent.com/clairehq/79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv
ภาพรวมคำสั่ง (Cheat Sheet) ของ pandas : https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
หมายเหตุ* เอกสารนี้ส่วนหนึ่งนำมาจาก Kaggle : https://www.kaggle.com/learn/pandas

In [22]:
import numpy as np
import pandas as pd

In [23]:
pd.DataFrame({'Yes': [50, 21,7], 'No': [131, 2,9]})
#เช่น “Row : 0, Column : No” Entry นี้มีค่า 131

   Yes   No
0   50  131
1   21    2
2    7    9

In [24]:
#ใน Entry ไม่จำเป็นต้องเป็นจำนวนเต็มอย่าง สามารถเป็นค่า String ก็ได้ เช่น
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [25]:
#โดยปกติแล้ว dictionary-list จะกำหนดค่าของ column labels 
#หรือค่า index แต่ละแถวให้ให้เริ่มต้นจาก 0 (0,1,2,3,...) แต่สามารถกำหนดค่าของ index ให้ได้ เช่นคำสั่ง
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

ในการใช้ Pandas จะมีข้อมูล object อีกรูปแบบหนึ่งนอกจาก DataFrame คือ Series
Series เป็นการจัดเรียงรายการข้อมูลแบบหนึ่งมิติ เหมือนกับโครงสร้างแบบ List ของภาษา Python คือมี Index กับ Value แต่ จะเป็นเสมือนการอ้างอิง value กับ index ในแต่ละแถว value อาจเป็น string, ตัวเลข ก็ได้ มีรูปแบบ คือ pd.Series(data, index, name, dtype)

In [26]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [27]:
pd.Series([30, 35, 40, 50], index=['2015 Sales', '2016 Sales', '2017 Sales', '2018 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
2018 Sales    50
Name: Product A, dtype: int64

In [28]:
s1 = pd.Series([1, 2, 3, 4, 5])

In [29]:
s1.mean()

3.0

In [30]:
s1.max()

5

In [31]:
s2 = pd.Series(["A", "B", "C"])

In [32]:
s2

0    A
1    B
2    C
dtype: object

In [33]:
df = pd.DataFrame({"name":s2, "working_years":s1})

In [34]:
df

  name  working_years
0    A              1
1    B              2
2    C              3
3  NaN              4
4  NaN              5

In [35]:
type(df)

pandas.core.frame.DataFrame

In [36]:
type(s1)

pandas.core.series.Series

In [37]:
df["name"]

0      A
1      B
2      C
3    NaN
4    NaN
Name: name, dtype: object

In [38]:
type(df["name"])

pandas.core.series.Series

In [39]:
df[["name"]]

  name
0    A
1    B
2    C
3  NaN
4  NaN

In [40]:
type(df[["name"]])

pandas.core.frame.DataFrame

1.3 การอ่านค่าจากไฟล์ CSV
	CSV คือ Comma-Seperated Values เป็นไฟล์ตารางที่เก็บค่าต่าง ๆ ที่แยกกันด้วยเครื่องหมาย commas : , 
	ในการอ่านไฟล์ จะใช้คำสั่ง pd.read_csv()
    คำสั่งนี้มี attribute ให้เลือกอ่านมาจำนวนมาก ศึกษาได้จาก : https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [41]:
df = pd.read_csv("https://raw.githubusercontent.com/lju-lazarevic/wine/master/data/winemag-data-130k-v2.csv")

In [42]:
# df.corr()

In [43]:
df

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

สำคัญ คือ ต้องกำหนด Directory ให้ถูกต้อง ถ้าโดยทั่วไปแล้ว สามารถเก็บไว้ใน Directory เดียวกันกับไฟล์ที่เรากำลังการเขียนโค้ด สามารถกำหนด ไปได้ทันที เช่น df = pd.read_csv(‘mydata.csv’) 
นอกจากนี้ ยังสามารถเรียกข้อมูลมาจากไฟล์แบบ อื่น ๆ ได้ เช่น excel file, HTML Table, JSON format 
ตัวอย่าง การเรียกจากไฟล์ html เช่น 
Data_path = https://data.go.th/dataset/49f4f6bc-b664-4b32-a206-d80e8d356e68/resource/f50cedc9-8486-422a-bb57-90a86135643e/download/webapp_research.csv
df = pd.read_csv(Data_path)

In [44]:
df.head(6)

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
5,97540,Austria,"). Phillip Zull's offering in the light, fresh...",Lust & Laune,87,12.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Zull 2010 Lust & Laune Grüner Veltliner (Niede...,Grüner Veltliner,Zull,NaN

In [45]:
df.shape

(119988, 15)

In [46]:
df.tail(9)

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
119979,111177,Chile,"Zippy, with natural rubbery aromas. This is qu...",NaN,84,8.0,Rapel Valley,NaN,NaN,Michael Schachner,@wineschach,Viña Santa Monica 2001 Riesling (Rapel Valley),Riesling,Viña Santa Monica,NaN
119980,97252,US,"Zippy, zesty acidity balances the ripe pear, l...",Boon's Fly Hill,92,50.0,California,Carneros,Napa-Sonoma,NaN,NaN,Kazmer & Blaise 2010 Boon's Fly Hill Chardonna...,Chardonnay,Kazmer & Blaise,NaN
119981,70889,Italy,Zisola is a Nero d'Avola that is aged 10 month...,NaN,90,23.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Zisola 2006 Nero d'Avola (Sicilia),Nero d'Avola,Zisola,NaN
119982,129643,US,Zocker flies under the radar with this Austria...,Paragon Vineyard,90,20.0,California,Edna Valley,Central Coast,NaN,NaN,Zocker 2012 Paragon Vineyard Grüner Veltliner ...,Grüner Veltliner,Zocker,NaN
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [47]:
df.sample()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
59876,99153,Spain,Peach and melon aromas are inviting and clean....,NaN,86,19.0,Northern Spain,Valdeorras,NaN,Michael Schachner,@wineschach,Viña Godeval 2009 Godello (Valdeorras),Godello,Viña Godeval,NaN

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119988 entries, 0 to 119987
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     119988 non-null  int64
 1   country                119929 non-null  object
 2   description            119988 non-null  object
 3   designation            85443 non-null   object
 4   points                 119988 non-null  int64
 5   price                  111593 non-null  float64
 6   province               119929 non-null  object
 7   region_1               100428 non-null  object
 8   region_2               46769 non-null   object
 9   taster_name            95071 non-null   object
 10  taster_twitter_handle  90542 non-null   object
 11  title                  119988 non-null  object
 12  variety                119987 non-null  object
 13  winery                 119988 non-null  object
 14  dupe?                  0 non-null       float64
dtypes: float64(2), int64(2), object(11)
memory usage: 13.7+ MB

In [49]:
#Export
df.to_csv("new_superwine.csv")

2. การเข้าถึง การเลือกและการกำหนดข้อมูล (Indexing, Selecting & Assigning)
Python นั้นมีการเข้าถึง index ต่าง ๆ ใน object ได้ง่าย โดยในที่นี้ สามารถเข้าถึง property ของ object ได้ เช่นจากตัวอย่าง อยากเข้าถึงคอลัมน์ Country สามารถใช้คำสั่งได้

In [50]:
df.country

0         Austria
1              US
2              US
3           Spain
4           Spain
           ...
119983      Italy
119984      Italy
119985      Italy
119986         US
119987    Austria
Name: country, Length: 119988, dtype: object

หรือใช้การเข้าถึงรูปแบบคล้ายๆ Dictionary ได้ ด้วย indexing operator ( [ ] ) เช่น หากต้องการเข้าถึงหรือต้องการแสดงผลข้อมูลเฉพาะคอลัมน์ country จะใช้คำสั่ง ดังนี้

In [51]:
df["country"]
#df.country

0         Austria
1              US
2              US
3           Spain
4           Spain
           ...
119983      Italy
119984      Italy
119985      Italy
119986         US
119987    Austria
Name: country, Length: 119988, dtype: object

In [52]:
df[["country"]]
#Transform to Dataframe
#ต่างกับด้านบน อย่างไร ?

        country
0       Austria
1            US
2            US
3         Spain
4         Spain
...         ...
119983    Italy
119984    Italy
119985    Italy
119986       US
119987  Austria

[119988 rows x 1 columns]

In [53]:
df[["country","points","taster_name"]]

        country  points        taster_name
0       Austria      85         Roger Voss
1            US      87     Virginie Boone
2            US      86                NaN
3         Spain      86  Michael Schachner
4         Spain      87  Michael Schachner
...         ...     ...                ...
119983    Italy      90                NaN
119984    Italy      88                NaN
119985    Italy      90                NaN
119986       US      87     Virginie Boone
119987  Austria      90   Anne Krebiehl MW

[119988 rows x 3 columns]

In [54]:
#หรือจะเลือกเฉพาะ index ของคอลัมน์ก็ได้ เช่น ต้องการเลือกข้อมูลที่ index ที่ 0 ของคอลัมน์ country ใช้คำสั่ง 
df['country'][0]

'Austria'

df[ลำดับคอลัมน์][ลำดับแถว]
rows selection
Indexing operator และการเลือกคอลัมน์หรือแอททริบิวต์ เพื่อใช้ในการวิเคราะห์ข้อมูลหรือกำหนดข้อมูลทำอะไรต่าง ๆ สามารถใช้คำสั่ง loc และ iloc 
โดย loc จะเป็นการเลือกแถวหรือคอลัมน์
และ iloc จะเป็นการเลือก index ของแถวหรือคอลัมน์ 
ทั้ง loc และ iloc คือแบบ “row-first, column-second’’ ตัวอย่างเช่น

In [55]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

In [56]:
df.iloc[4]
#row first,column second

id                                                                  119752
country                                                              Spain
description              ). Light and lemony on the nose. The palate ha...
designation                                                            NaN
points                                                                  87
price                                                                 17.0
province                                                           Galicia
region_1                                                       Rías Baixas
region_2                                                               NaN
taster_name                                              Michael Schachner
taster_twitter_handle                                          @wineschach
title                                  La Caña 2010 Albariño (Rías Baixas)
variety                                                           Albariño
winery                                                             La Caña
dupe?                                                                  NaN
Name: 4, dtype: object

In [57]:
df.iloc[[15230]]

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
15230,62556,Australia,"An icon in Australia, Mount Mary has never mad...",Quintet,88,145.0,Victoria,Yarra Valley,NaN,Joe Czerwinski,@JoeCz,Mount Mary 2005 Quintet Red (Yarra Valley),Bordeaux-style Red Blend,Mount Mary,NaN

Operator (:) คือ “everything” (เลือกทั้งหมด) หรือเรียกว่า “Index Slicing” โดยมีหลักการคือ df[start : stop : step]
เช่น หากต้องการเลือกแถวสามแถวแรก (:3) และเลือกคอลัมน์แรก (0 ข้างหลัง)

In [58]:
df.iloc[:7,10]             # 1 2 3 4

0     @vossroger
1        @vboone
2            NaN
3    @wineschach
4    @wineschach
5     @vossroger
6            NaN
Name: taster_twitter_handle, dtype: object

In [59]:
df.iloc[:4, :5]

,id,country,description,designation,points
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86

In [60]:
df.iloc[1:3,0]

1    126883
2    119493
Name: id, dtype: int64

In [61]:
#หรืออีกแบบหนึ่ง ใช้ iloc เลือกแถวที่ index 0,1,2 และคอลัมน์แรก (0) 
df.iloc[[0,1,2],0]

0     94355
1    126883
2    119493
Name: id, dtype: int64

In [62]:
df.iloc[-5:]

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

Label-based selection

In [63]:
df.loc[0]

id                                                                   94355
country                                                            Austria
description              "Chremisa," the ancient name of Krems, is comm...
designation                                  Edition Chremisa Sandgrube 13
points                                                                  85
price                                                                 24.0
province                                                  Niederösterreich
region_1                                                               NaN
region_2                                                               NaN
taster_name                                                     Roger Voss
taster_twitter_handle                                           @vossroger
title                    Winzer Krems 2011 Edition Chremisa Sandgrube 1...
variety                                                   Grüner Veltliner
winery                                                        Winzer Krems
dupe?                                                                  NaN
Name: 0, dtype: object

In [64]:
df.loc[:10,'country']

0     Austria
1          US
2          US
3       Spain
4       Spain
5     Austria
6       Italy
7          US
8          US
9          US
10         US
Name: country, dtype: object

In [65]:
df.loc[[0]]

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN

In [66]:
df.loc[1,['country','points']]

country    US
points     87
Name: 1, dtype: object

In [67]:
df.loc[[41649],['country','points']]

      country  points
41649      US      80

In [68]:
df.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

              taster_name taster_twitter_handle  points
0              Roger Voss            @vossroger      85
1          Virginie Boone               @vboone      87
2                     NaN                   NaN      86
3       Michael Schachner           @wineschach      86
4       Michael Schachner           @wineschach      87
...                   ...                   ...     ...
119983                NaN                   NaN      90
119984                NaN                   NaN      88
119985                NaN                   NaN      90
119986     Virginie Boone               @vboone      87
119987   Anne Krebiehl MW           @AnneInVino      90

[119988 rows x 3 columns]

2.3 การจัดการ Index (Manipulating the index)
	Index สามารถจัดการด้วยคำสั่ง set_index() 
เช่น ต้องการให้ title เป็น index ของ Data Frame นี้ จะใช้คำสั่ง

In [69]:
df.set_index("title")

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,dupe?
title,,,,,,,,,,,,,,
Winzer Krems 2011 Edition Chremisa Sandgrube 13 Grüner Veltliner (Niederösterreich),94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Grüner Veltliner,Winzer Krems,NaN
Line 39 2009 Cabernet Sauvignon (North Coast),126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Cabernet Sauvignon,Line 39,NaN
Jamieson Ranch 2011 Whiplash Chardonnay (California),119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Chardonnay,Jamieson Ranch,NaN
Emilio Moro 2009 Finca Resalso (Ribera del Duero),126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Tinto Fino,Emilio Moro,NaN
La Caña 2010 Albariño (Rías Baixas),119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ceretto 2004 Zonchera (Barolo),80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Nebbiolo,Ceretto,NaN
Zonin 2006 Amarone della Valpolicella,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,"Corvina, Rondinella, Molinara",Zonin,NaN
Zorzettig 2006 Picolit (Colli Orientali del Friuli),86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Picolit,Zorzettig,NaN
Zucca 2010 Sangiovese Rosato Rosé (Amador County),18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Rosé,Zucca,NaN
Nittnaus Hans und Christine 2013 Heideboden Zweigelt (Burgenland),88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Zweigelt,Nittnaus Hans und Christine,NaN

2.4 การเลือกตามเงื่อนไข (Conditional Selection)
	จากการทำการ indexing นั้น เราสามารถนำผลลัพธ์ที่ได้จากการเลือกแอททริบิวต์ที่สนใจ มาทำการตรวจสอบเงื่อนไขได้ ตัวอย่าง เช่น หากต้องการตรวจสอบรายละเอียดไวน์ที่ผลิตจาก Italy

In [70]:
df.country == 'Italy'

0         False
1         False
2         False
3         False
4         False
          ...
119983     True
119984     True
119985     True
119986    False
119987    False
Name: country, Length: 119988, dtype: bool

การใช้ Operation แบบนี้แสดงออกมาเป็น Boolean (True/False) หมายถึง แต่ละแถวมี Italy หรือไม่ ? 
 Operation นี้ จะใช้ตรวจสอบว่าแต่ละ record หรือแต่ละแถว เป็น Italy หรือไม่ด้วย loc

In [71]:
df.loc[df.country == 'Austria']

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
5,97540,Austria,"). Phillip Zull's offering in the light, fresh...",Lust & Laune,87,12.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Zull 2010 Lust & Laune Grüner Veltliner (Niede...,Grüner Veltliner,Zull,NaN
52,109183,Austria,2015's ripe red cherry fruit is presented here...,NaN,90,18.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Anita und Hans 2015 Zweigelt (Burgenl...,Zweigelt,Nittnaus Anita und Hans,NaN
55,99983,Austria,500 ml. Almost as intensely spicy as an Alsace...,Loibner Smaragd 500ml,88,34.0,Wachau,NaN,NaN,Roger Voss,@vossroger,Emmerich Knoll 2008 Loibner Smaragd 500ml Tram...,Traminer,Emmerich Knoll,NaN
871,56801,Austria,A 900-foot vineyard offers just the right cool...,Dürr,90,NaN,Burgenland,NaN,NaN,Roger Voss,@vossroger,Kollwentz 2007 Dürr Pinot Noir (Burgenland),Pinot Noir,Kollwentz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119936,75737,Austria,"Zesty, superfresh citrus and apple notes set t...",Flaschengärung,89,30.0,Österreichischer Sekt,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Steininger 2012 Flaschengärung Grüner Veltline...,Grüner Veltliner,Steininger,NaN
119960,13305,Austria,"Zingy and restrained Sauvignon Blanc, none of ...",Steinriegl,90,28.0,Südsteiermark,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Wohlmuth 2014 Steinriegl Sauvignon Blanc (Süds...,Sauvignon Blanc,Wohlmuth,NaN
119964,17324,Austria,Zingy lime peel keeps a tight handle on the mo...,Steirische Klassik,89,NaN,Südsteiermark,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Gross 2013 Steirische Klassik Sauvignon Blanc ...,Sauvignon Blanc,Gross,NaN
119978,68285,Austria,"Zippy, fresh conference pear fruit with just a...",NaN,90,17.0,Kamptal,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Steininger 2014 Grüner Veltliner (Kamptal),Grüner Veltliner,Steininger,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

เราสามารถใช้คำสั่ง and ด้วยเครื่องหมาย ampersand ( & ) หรือคำสั่ง or ด้วยเครื่องหมาย pipe ( | ) ได้
เช่น หากต้องการทราบไวน์อิตาลีและได้คะแนน (points) มากกว่า 90 จะใช้คำสั่ง

In [72]:
df.loc[(df.country == 'Italy') & (df.points >=90)]

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
18,23362,Italy,". There's a compact, traditional characteristi...",Vigneto Bellavista,90,169.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Castello di Ama 2006 Vigneto Bellavista (Chia...,Sangiovese,Castello di Ama,NaN
20,76094,Italy,. This rich and opulent blend of Cabernet Sauv...,Volpolo,92,50.0,Tuscany,Bolgheri,NaN,NaN,NaN,Podere Sapaio 2008 Volpolo (Bolgheri),Red Blend,Podere Sapaio,NaN
28,83416,Italy,"100% Cabernet Sauvignon, this opens with aroma...",Basilica del Cortaccio,91,40.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Cafaggio 2010 Basilica del Cortaccio Cabernet ...,Cabernet Sauvignon,Cafaggio,NaN
705,4515,Italy,95 Massolino 2012 Parafada (Barolo). A textb...,Parafada,95,96.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Massolino 2012 Parafada (Barolo),Nebbiolo,Massolino,NaN
810,81278,Italy,"A 25th anniversary special selection, this bea...",Selezione XXV Anno,93,60.0,Tuscany,Brunello di Montalcino,NaN,NaN,NaN,Castello Romitorio 2006 Selezione XXV Anno (B...,Sangiovese Grosso,Castello Romitorio,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119847,54397,Italy,Zenato is a reliable producer of quality Amaro...,NaN,92,30.0,Veneto,Amarone della Valpolicella Classico,NaN,NaN,NaN,Zenato 2008 Amarone della Valpolicella Classico,"Corvina, Rondinella, Molinara",Zenato,NaN
119848,59349,Italy,Zenato's rich and powerful Recioto opens with ...,500 ml,90,NaN,Veneto,Recioto della Valpolicella Classico,NaN,NaN,NaN,Zenato 2006 500 ml (Recioto della Valpolicell...,"Corvina, Rondinella, Molinara",Zenato,NaN
119981,70889,Italy,Zisola is a Nero d'Avola that is aged 10 month...,NaN,90,23.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Zisola 2006 Nero d'Avola (Sicilia),Nero d'Avola,Zisola,NaN
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN

หากต้องการทราบไวน์อิตาลี หรือ ไวน์ที่ได้คะแนน (points) มากกว่าหรือเท่ากับ 90 จะใช้คำสั่ง

In [73]:
df.loc[(df.country == 'Italy') | (df.points >=90)]

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
6,115413,Italy,). Rubiolo is a soft and lush Chianti Classico...,Rubiolo,88,23.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Gagliole 2009 Rubiolo (Chianti Classico),Sangiovese,Gagliole,NaN
8,29339,US,). Very good wine from a winery increasingly k...,Rockpile Ridge Vineyard,92,47.0,California,Rockpile,Sonoma,NaN,NaN,Mauritson 2009 Rockpile Ridge Vineyard Caberne...,Cabernet Sauvignon,Mauritson,NaN
9,98444,US,). Vineyard 7&8's Spring Mountain Estate Caber...,Estate,94,125.0,California,Spring Mountain District,Napa,NaN,NaN,Vineyard 7&8 2009 Estate Cabernet Sauvignon (S...,Cabernet Sauvignon,Vineyard 7&8,NaN
10,60042,US,). You'll want to cellar this young 100% Cab b...,Family Reserve,93,145.0,California,Napa Valley,Napa,NaN,NaN,Venge 2010 Family Reserve Cabernet Sauvignon (...,Cabernet Sauvignon,Venge,NaN
11,62258,US,. A delightfully intriguing “White Burgundy” b...,White Burgundy,90,29.0,California,North Coast,North Coast,Virginie Boone,@vboone,Imagery 2009 White Burgundy White (North Coast),White Blend,Imagery,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119982,129643,US,Zocker flies under the radar with this Austria...,Paragon Vineyard,90,20.0,California,Edna Valley,Central Coast,NaN,NaN,Zocker 2012 Paragon Vineyard Grüner Veltliner ...,Grüner Veltliner,Zocker,NaN
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [74]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

In [75]:
df[["country"]]

        country
0       Austria
1            US
2            US
3         Spain
4         Spain
...         ...
119983    Italy
119984    Italy
119985    Italy
119986       US
119987  Austria

[119988 rows x 1 columns]

In [76]:
df["country"] = 'Italy'

In [77]:
df
#แทนค่าทุกค่าในคอลัมน์ country เป็น Italy หมด !!

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Italy,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,Italy,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,Italy,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Italy,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Italy,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,Italy,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Italy,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [78]:
df = pd.read_csv("https://raw.githubusercontent.com/lju-lazarevic/wine/master/data/winemag-data-130k-v2.csv")

In [79]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

In [80]:
df[df['country'] == 'Italy']
#df.loc[df.country == 'Italy']

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
6,115413,Italy,). Rubiolo is a soft and lush Chianti Classico...,Rubiolo,88,23.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Gagliole 2009 Rubiolo (Chianti Classico),Sangiovese,Gagliole,NaN
18,23362,Italy,". There's a compact, traditional characteristi...",Vigneto Bellavista,90,169.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Castello di Ama 2006 Vigneto Bellavista (Chia...,Sangiovese,Castello di Ama,NaN
20,76094,Italy,. This rich and opulent blend of Cabernet Sauv...,Volpolo,92,50.0,Tuscany,Bolgheri,NaN,NaN,NaN,Podere Sapaio 2008 Volpolo (Bolgheri),Red Blend,Podere Sapaio,NaN
28,83416,Italy,"100% Cabernet Sauvignon, this opens with aroma...",Basilica del Cortaccio,91,40.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Cafaggio 2010 Basilica del Cortaccio Cabernet ...,Cabernet Sauvignon,Cafaggio,NaN
705,4515,Italy,95 Massolino 2012 Parafada (Barolo). A textb...,Parafada,95,96.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Massolino 2012 Parafada (Barolo),Nebbiolo,Massolino,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119941,1349,Italy,Zibibbo is usually presented as a passito dess...,NaN,86,35.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Barraco 2010 Zibibbo (Sicilia),Zibibbo,Barraco,NaN
119981,70889,Italy,Zisola is a Nero d'Avola that is aged 10 month...,NaN,90,23.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Zisola 2006 Nero d'Avola (Sicilia),Nero d'Avola,Zisola,NaN
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN

df['country'] == 'Italy' → เป็นการสร้างเงื่อนไขที่คืนค่า True สำหรับแถวที่มีค่า country เท่ากับ "Italy"
df[df['country'] == 'Italy'] → ใช้เงื่อนไขที่ได้มาเพื่อเลือกเฉพาะแถวที่มีค่า True

In [81]:
df[df["country"]=='Italy'][["price","province", "title"]]

,price,province,title
6,23.0,Tuscany,Gagliole 2009 Rubiolo (Chianti Classico)
18,169.0,Tuscany,Castello di Ama 2006 Vigneto Bellavista (Chia...
20,50.0,Tuscany,Podere Sapaio 2008 Volpolo (Bolgheri)
28,40.0,Tuscany,Cafaggio 2010 Basilica del Cortaccio Cabernet ...
705,96.0,Piedmont,Massolino 2012 Parafada (Barolo)
...,...,...,...
119941,35.0,Sicily & Sardinia,Barraco 2010 Zibibbo (Sicilia)
119981,23.0,Sicily & Sardinia,Zisola 2006 Nero d'Avola (Sicilia)
119983,48.0,Piedmont,Ceretto 2004 Zonchera (Barolo)
119984,70.0,Veneto,Zonin 2006 Amarone della Valpolicella
119985,NaN,Northeastern Italy,Zorzettig 2006 Picolit (Colli Orientali del Fr...

In [82]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

การใช้คำสั่ง isin เป็นการเลือก
เช่น การตรวจสอบว่ามีไวน์จากอิตาลีหรือฝรั่งเศส หรือไม่

In [83]:
df.loc[df.country.isin(['Italy','France'])]

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
6,115413,Italy,). Rubiolo is a soft and lush Chianti Classico...,Rubiolo,88,23.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Gagliole 2009 Rubiolo (Chianti Classico),Sangiovese,Gagliole,NaN
16,101344,France,. Recent vintages have left Bordeaux with an a...,NaN,87,17.0,Bordeaux,Bordeaux Supérieur,NaN,Roger Voss,@vossroger,Château Sainte-Barbe 2010 Bordeaux Supérieur,Bordeaux-style Red Blend,Château Sainte-Barbe,NaN
18,23362,Italy,". There's a compact, traditional characteristi...",Vigneto Bellavista,90,169.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Castello di Ama 2006 Vigneto Bellavista (Chia...,Sangiovese,Castello di Ama,NaN
20,76094,Italy,. This rich and opulent blend of Cabernet Sauv...,Volpolo,92,50.0,Tuscany,Bolgheri,NaN,NaN,NaN,Podere Sapaio 2008 Volpolo (Bolgheri),Red Blend,Podere Sapaio,NaN
28,83416,Italy,"100% Cabernet Sauvignon, this opens with aroma...",Basilica del Cortaccio,91,40.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Cafaggio 2010 Basilica del Cortaccio Cabernet ...,Cabernet Sauvignon,Cafaggio,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119947,98934,France,Zind-Humbrecht owns some great Grand Cru viney...,Clos Saint Urbain Rangen de Thann Grand Cru,94,105.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Zind-Humbrecht 2012 Clos Saint Urbain ...,Pinot Gris,Domaine Zind-Humbrecht,NaN
119981,70889,Italy,Zisola is a Nero d'Avola that is aged 10 month...,NaN,90,23.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Zisola 2006 Nero d'Avola (Sicilia),Nero d'Avola,Zisola,NaN
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN

หรือใช้คำสั่ง notnull เพื่อตรวจสอบข้อมูลที่ไม่มึค่า null 
เช่น นำไวน์ที่ไม่มี price tag ออกไป

In [84]:
df.loc[df.price.notnull()]

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119982,129643,US,Zocker flies under the radar with this Austria...,Paragon Vineyard,90,20.0,California,Edna Valley,Central Coast,NaN,NaN,Zocker 2012 Paragon Vineyard Grüner Veltliner ...,Grüner Veltliner,Zocker,NaN
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119986,18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

นอกจากนี้ ยังสามารถกำหนดข้อมูล (Assigning Data) ให้ได้ เช่น

In [85]:
df['description'] = 'details'

In [86]:
df['description']

0         details
1         details
2         details
3         details
4         details
           ...
119983    details
119984    details
119985    details
119986    details
119987    details
Name: description, Length: 119988, dtype: object

การลบแถวและคอลัมน์ 
การลบคอลัมน์ด้วยคำสั่ง .drop()

In [87]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,details,Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,details,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,details,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,details,Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,details,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

In [88]:
df.drop(2)

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,details,Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,details,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
3,126909,Spain,details,Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,details,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
5,97540,Austria,details,Lust & Laune,87,12.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Zull 2010 Lust & Laune Grüner Veltliner (Niede...,Grüner Veltliner,Zull,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119983,80210,Italy,details,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,details,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,details,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,US,details,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Austria,details,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [89]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,details,Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,details,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,details,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,details,Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,details,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

In [90]:
df.drop(4, inplace=True)
#ทำการเปลี่ยนแปลงใน DataFrame เดิมโดยตรง หากไม่ได้ระบุ 
#(inplace=False ซึ่งเป็นค่าเริ่มต้น) จะคืนค่าข้อมูลในรูปแบบ DataFrame ใหม่

In [91]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,details,Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,details,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,details,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,details,Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
5,97540,Austria,details,Lust & Laune,87,12.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Zull 2010 Lust & Laune Grüner Veltliner (Niede...,Grüner Veltliner,Zull,NaN

In [92]:
df.drop('country', axis=1)

,id,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,details,Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,details,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,details,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,details,Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
5,97540,details,Lust & Laune,87,12.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Zull 2010 Lust & Laune Grüner Veltliner (Niede...,Grüner Veltliner,Zull,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119983,80210,details,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,details,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,details,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,details,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,details,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [93]:
df[['country','points']]

        country  points
0       Austria      85
1            US      87
2            US      86
3         Spain      86
5       Austria      87
...         ...     ...
119983    Italy      90
119984    Italy      88
119985    Italy      90
119986       US      87
119987  Austria      90

[119987 rows x 2 columns]

In [94]:
df.loc[0,'country'] = 'Thailand'

In [95]:
df[['country','points']]

         country  points
0       Thailand      85
1             US      87
2             US      86
3          Spain      86
5        Austria      87
...          ...     ...
119983     Italy      90
119984     Italy      88
119985     Italy      90
119986        US      87
119987   Austria      90

[119987 rows x 2 columns]

In [96]:
df.loc[[1,2],'country'] = 'Thailandzzz'

In [97]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Thailand,details,Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,Thailandzzz,details,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,Thailandzzz,details,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,details,Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
5,97540,Austria,details,Lust & Laune,87,12.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Zull 2010 Lust & Laune Grüner Veltliner (Niede...,Grüner Veltliner,Zull,NaN

In [98]:
df.loc[[1,2],['country','points']] = 'MODIFIED'

C:\Users\Tanadon\AppData\Local\Temp\ipykernel_40600\1957196632.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'MODIFIED' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[[1,2],['country','points']] = 'MODIFIED'

In [99]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Thailand,details,Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,MODIFIED,details,NaN,MODIFIED,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,MODIFIED,details,Whiplash,MODIFIED,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,details,Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
5,97540,Austria,details,Lust & Laune,87,12.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Zull 2010 Lust & Laune Grüner Veltliner (Niede...,Grüner Veltliner,Zull,NaN

reload again !

In [100]:
df = pd.read_csv("https://raw.githubusercontent.com/lju-lazarevic/wine/master/data/winemag-data-130k-v2.csv")

3. Summary Functions and Maps
Pandas มีฟังก์ชันสำหรับช่วยในการสรุปข้อมูลต่าง ๆ เช่น จำนวน ค่าเฉลี่ย ค่าสูงสุด ฯลฯ เพื่อช่วยในการรวบรวมข้อมูล เช่น คำสั่ง describe() เช่น ในกรณีนี้ต้องการทราบ summary ของ คะแนนของไวน์

In [101]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

In [102]:
df.describe()

                  id         points          price  dupe?
count  119988.000000  119988.000000  111593.000000    0.0
mean    63214.087509      88.442236      35.620747    NaN
std     37505.899183       3.092915      42.103728    NaN
min         0.000000      80.000000       4.000000    NaN
25%     30501.750000      86.000000      17.000000    NaN
50%     62405.500000      88.000000      25.000000    NaN
75%     95388.250000      91.000000      42.000000    NaN
max    129970.000000     100.000000    3300.000000    NaN

In [103]:
df.points.describe()

count    119988.000000
mean         88.442236
std           3.092915
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [104]:
df.country.describe()

count     119929
unique        43
top           US
freq       50457
Name: country, dtype: object

In [105]:
df.points.mean()

88.44223589025569

In [106]:
df.points.sum()

10612007

In [107]:
df.points.median()

88.0

In [108]:
df.points.mode()

0    88
Name: points, dtype: int64

In [109]:
df.points.std()

3.092915286828905

In [110]:
df.points.max()

100

In [111]:
df.points.min()

80

In [112]:
df.points.abs()

0         85
1         87
2         86
3         86
4         87
          ..
119983    90
119984    88
119985    90
119986    87
119987    90
Name: points, Length: 119988, dtype: int64

คำสั่งที่ต้องการ unique value ด้วย .unique() หรือในคอลัมน์นั้น ๆ มีชื่อเฉพาะ หรือค่าเฉพาะ ค่าใดบ้าง 
หรือคำสั่งในการนับจำนวน ด้วย value_counts() เช่น ต้องการนับจำนวนชื่อผู้ชิมไวน์ (taster_name) 
คำสั่ง Maps ใช้สำหรับในการ Transformation ข้อมูล เช่นต้องการทราบคะแนน (point) ของไวน์ที่ได้รับว่าต่างจาก mean แค่ไหน เช่น

In [113]:
df.taster_name.unique()

array(['Roger Voss', 'Virginie Boone', nan, 'Michael Schachner',
       'Anna Lee C. Iijima', 'Paul Gregutt', 'Sean P. Sullivan',
       'Kerin O’Keefe', 'Anne Krebiehl\xa0MW', 'Lauren Buzzeo',
       'Joe Czerwinski', 'Alexander Peartree', 'Matt Kettmann',
       'Jim Gordon', 'Susan Kostrzewa', 'Mike DeSimone', 'Jeff Jenssen',
       'Christina Pickard', 'Carrie Dykes', 'Fiona Adams'], dtype=object)

In [114]:
df.taster_name.value_counts()

taster_name
Roger Voss            23560
Michael Schachner     14046
Kerin O’Keefe          9697
Paul Gregutt           8868
Virginie Boone         8708
Matt Kettmann          5730
Joe Czerwinski         4766
Sean P. Sullivan       4461
Anna Lee C. Iijima     4017
Jim Gordon             3766
Anne Krebiehl MW       3290
Lauren Buzzeo          1700
Susan Kostrzewa        1023
Mike DeSimone           461
Jeff Jenssen            436
Alexander Peartree      383
Carrie Dykes            129
Fiona Adams              24
Christina Pickard         6
Name: count, dtype: int64

In [115]:
review_points_mean = df.points.mean()
df.points.map(lambda p: p - review_points_mean)

0        -3.442236
1        -1.442236
2        -2.442236
3        -2.442236
4        -1.442236
            ...
119983    1.557764
119984   -0.442236
119985    1.557764
119986   -1.442236
119987    1.557764
Name: points, Length: 119988, dtype: float64

คำสั่ง .apply() จะใช้ในการแปลงข้อมูลในแต่ละคอลัมน์

In [116]:
def remean_points(row):
    row.points = row.points - review_points_mean
    return row

df.apply(remean_points, axis='columns')

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,-3.442236,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,-1.442236,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,-2.442236,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,-2.442236,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,-1.442236,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,1.557764,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,-0.442236,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,1.557764,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,-1.442236,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,1.557764,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [117]:
df.head()

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN

In [118]:
#Reload Again 
df = pd.read_csv("https://raw.githubusercontent.com/lju-lazarevic/wine/master/data/winemag-data-130k-v2.csv")

In [119]:
import numpy as np
np.log10(1000)

3.0

In [120]:
df["points"]

0         85
1         87
2         86
3         86
4         87
          ..
119983    90
119984    88
119985    90
119986    87
119987    90
Name: points, Length: 119988, dtype: int64

In [121]:
df["points"].apply(np.log10)

0         1.929419
1         1.939519
2         1.934498
3         1.934498
4         1.939519
            ...
119983    1.954243
119984    1.944483
119985    1.954243
119986    1.939519
119987    1.954243
Name: points, Length: 119988, dtype: float64

In [122]:
df.points.apply(np.sqrt)

0         9.219544
1         9.327379
2         9.273618
3         9.273618
4         9.327379
            ...
119983    9.486833
119984    9.380832
119985    9.486833
119986    9.327379
119987    9.486833
Name: points, Length: 119988, dtype: float64

4. Grouping and Sorting
4.1 Groupwise 
	เนื่องจาก Data Frame เป็นข้อมูลแบบสองมิติที่อาจมีมากกว่าหนึ่งคอลัมน์ บางครั้งอาจมีบางคอลัมน์ที่ข้อมูลซ้ำซ้อนกัน ซึ่งสามารถนำมาจัดกลุ่มได้ และอาจใช้มากกว่าหนึ่งคอลัมน์ โดยใช้ฟังก์ชัน groupby() ในการจัดกลุ่ม และยังสามารถตามด้วยฟังก์ชันทางสถิติต่าง ๆ (sum(), count(), mean(), min(), max() ) เพื่อให้ได้ผลลัพธ์ตามที่ต้องการ
ตัวอย่าง จากคำสั่ง groupby() และ value_counts
Groupby จะใช้สร้างกลุ่มของ review ที่มีคะแนนเหมือนกัน จากนั้นในแต่ละ group จะแสดงว่ามีจำนวนเท่าไหร่ที่มีคะแนนเหมือนกันในอีกคอลัมน์ หนึ่ง
เช่นเดียวกัน สามารถจับกลุ่ม เช่น หาราคาไวน์ที่ถูกที่สุดในแต่ละคะแนน (points)

In [123]:
df.groupby('points').points.count()

points
80       397
81       689
82      1814
83      2963
84      6225
85      9067
86     11526
87     15279
88     15291
89     11147
90     13893
91     10559
92      8951
93      6170
94      3625
95      1514
96       521
97       228
98        77
99        33
100       19
Name: points, dtype: int64

In [124]:
df.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [125]:
df.groupby('country').price.min()

country
Argentina                  4.0
Armenia                   14.0
Australia                  5.0
Austria                    7.0
Bosnia and Herzegovina    12.0
Brazil                    10.0
Bulgaria                   8.0
Canada                    12.0
Chile                      5.0
China                     18.0
Croatia                   12.0
Cyprus                    11.0
Czech Republic            15.0
Egypt                      NaN
England                   25.0
France                     5.0
Georgia                    9.0
Germany                    5.0
Greece                     8.0
Hungary                   10.0
India                     10.0
Israel                     8.0
Italy                      5.0
Lebanon                   13.0
Luxembourg                16.0
Macedonia                 15.0
Mexico                     8.0
Moldova                    8.0
Morocco                   14.0
New Zealand                7.0
Peru                      10.0
Portugal                   5.0
Romania                    4.0
Serbia                    15.0
Slovakia                  16.0
Slovenia                   7.0
South Africa               5.0
Spain                      4.0
Switzerland               21.0
Turkey                    14.0
US                         4.0
Ukraine                    6.0
Uruguay                   10.0
Name: price, dtype: float64

In [126]:
df.groupby(['country','points']).price.min()

country    points
Argentina  80         5.0
           81         6.0
           82         6.0
           83         6.0
           84         4.0
                     ...
Uruguay    88        13.0
           89        16.0
           90        20.0
           91        22.0
           92        43.0
Name: price, Length: 463, dtype: float64

In [127]:
#คำสั่ง .agg() ทำให้เรียกใช้ฟังก์ชันต่าง ๆ เช่น จำนวน ค่าน้อยสุด มากสุด ได้ เช่น 
df.groupby(['country']).price.agg([len, min, max])

C:\Users\Tanadon\AppData\Local\Temp\ipykernel_40600\1486848236.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(['country']).price.agg([len, min, max])
C:\Users\Tanadon\AppData\Local\Temp\ipykernel_40600\1486848236.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(['country']).price.agg([len, min, max])

                          len   min     max
country
Argentina                3544   4.0   230.0
Armenia                     2  14.0    15.0
Australia                2197   5.0   850.0
Austria                  3034   7.0  1100.0
Bosnia and Herzegovina      2  12.0    13.0
Brazil                     49  10.0    60.0
Bulgaria                  132   8.0   100.0
Canada                    226  12.0   120.0
Chile                    4184   5.0   400.0
China                       1  18.0    18.0
Croatia                    70  12.0    65.0
Cyprus                     10  11.0    21.0
Czech Republic             11  15.0    45.0
Egypt                       1   NaN     NaN
England                    63  25.0    95.0
France                  20353   5.0  3300.0
Georgia                    76   9.0    40.0
Germany                  1992   5.0   775.0
Greece                    432   8.0    79.0
Hungary                   129  10.0   764.0
India                       8  10.0    20.0
Israel                    466   8.0   150.0
Italy                   17940   5.0   900.0
Lebanon                    32  13.0    75.0
Luxembourg                  5  16.0    30.0
Macedonia                  11  15.0    20.0
Mexico                     68   8.0   108.0
Moldova                    56   8.0    42.0
Morocco                    24  14.0    40.0
New Zealand              1278   7.0   130.0
Peru                       16  10.0    68.0
Portugal                 5256   5.0  1000.0
Romania                   102   4.0   320.0
Serbia                      8  15.0    42.0
Slovakia                    1  16.0    16.0
Slovenia                   77   7.0    90.0
South Africa             1301   5.0   330.0
Spain                    6116   4.0   770.0
Switzerland                 6  21.0   160.0
Turkey                     81  14.0   120.0
US                      50457   4.0  2013.0
Ukraine                    14   6.0    13.0
Uruguay                    98  10.0   130.0

In [128]:
countries_reviewed = df.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3038
          Other              506
Armenia   Armenia              2
Australia Australia Other    231
          New South Wales     82
...                          ...
Uruguay   Juanico             11
          Montevideo          10
          Progreso            11
          San Jose             3
          Uruguay             23

[425 rows x 1 columns]

4.2 การจัดเรียงข้อมูล (Sorting)
	ข้อมูลจากการทำ groupby อาจไม่ได้ทำการเรียงลำดับมาก่อน การใช้คำสั่ง sort_values() จะช่วยในการเรียงลำดับ ได้ เช่น

In [129]:
#SORTING
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

      country           province    len
316    Serbia           Pocerina      1
386    Turkey  Elazığ-Diyarbakir      1
94    Croatia            Croatia      1
192    Greece      Sterea Ellada      1
301  Portugal      Vinho da Mesa      1
..        ...                ...    ...
409        US             Oregon   4929
227     Italy            Tuscany   5391
118    France           Bordeaux   5556
415        US         Washington   7965
392        US         California  33656

[425 rows x 3 columns]

ปกติแล้ว default จะเป็นแบบ ascending (น้อยไปมาก) เราสามารถเปลี่ยนเป็น descending (มากไปน้อย) ได้โดยชึ้คำสั่ง ascending = False ตัวอย่าง เช่น

In [130]:
countries_reviewed.sort_values(by='len', ascending=False)

     country                   province    len
392       US                 California  33656
415       US                 Washington   7965
118   France                   Bordeaux   5556
227    Italy                    Tuscany   5391
409       US                     Oregon   4929
..       ...                        ...    ...
176   Greece                   Messinia      1
386   Turkey          Elazığ-Diyarbakir      1
174   Greece  Mavrodaphne de Cephalonie      1
389   Turkey                Urla-Thrace      1
97   Croatia          Hrvatsko Primorje      1

[425 rows x 3 columns]

In [131]:
#การ Sort ตาม index สามารถทำได้ ด้วยคำสั่ง sort_index() 
countries_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3038
1    Argentina             Other   506
2      Armenia           Armenia     2
3    Australia   Australia Other   231
4    Australia   New South Wales    82
..         ...               ...   ...
420    Uruguay           Juanico    11
421    Uruguay        Montevideo    10
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    23

[425 rows x 3 columns]

In [132]:
#และยังสามารถ sort ได้มากกว่าหนึ่งคอลัมน์ เช่น ต้องการเรียงลำดับตามประเทศ (country) และ len
countries_reviewed.sort_values(by=['country', 'len'])

       country          province   len
1    Argentina             Other   506
0    Argentina  Mendoza Province  3038
2      Armenia           Armenia     2
6    Australia          Tasmania    36
4    Australia   New South Wales    82
..         ...               ...   ...
421    Uruguay        Montevideo    10
420    Uruguay           Juanico    11
422    Uruguay          Progreso    11
424    Uruguay           Uruguay    23
419    Uruguay         Canelones    35

[425 rows x 3 columns]

5. Data Types and Missing Value
5.1 Dtype 
	ชนิดของข้อมูลในแต่ละคอลัมน์ของ DataFrame ตรวจสอบได้ด้วยคำสั่ง dtype เช่น

In [133]:
df.price.dtype

dtype('float64')

In [134]:
df.dtypes

id                         int64
country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dupe?                    float64
dtype: object

In [135]:
#การเปลี่ยนหน่วยของ data type ด้วย astype() เช่น
df.points.astype('float64')

0         85.0
1         87.0
2         86.0
3         86.0
4         87.0
          ...
119983    90.0
119984    88.0
119985    90.0
119986    87.0
119987    90.0
Name: points, Length: 119988, dtype: float64

In [136]:
df.index.dtype

dtype('int64')

5.2 Missing Data
	Entries ที่ไม่ปรากฏข้อมูลหรือข้อมูลที่หายไปจะแสดง NaN ขึ้นมา (Not a Number) 
	คำสั่งที่ใช้ตรวจสอบว่ามี NaN ใน pandas ใช้คำสั่ง pd.isnull() (ถ้าตรวจว่าไม่ใช่ NaN จะเป็นคำสั่ง pd.notnull()

In [137]:
df[pd.isnull(df.country)]

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
1938,129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ,NaN
2088,11150,NaN,"A blend of 85% Melnik, 10% Grenache Noir and 5...",NaN,89,20.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Orbelus 2013 Melnik,Melnik,Orbelus,NaN
3857,46352,NaN,"A dark color and rich, jammy, baked aromas of ...",Catalina,91,50.0,NaN,NaN,NaN,Michael Schachner,@wineschach,Santa Ema 2014 Catalina Red,Red Blend,Santa Ema,NaN
6779,105167,NaN,"A lively whiff of white blossom, Muscat grapes...",Steirische Klassik,92,21.0,NaN,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Neumeister 2016 Steirische Klassik Gelber Musk...,Gelber Muskateller,Neumeister,NaN
7349,85821,NaN,A neutral nose leads onto an apple-fresh palat...,Steirische Klassik,90,22.0,NaN,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Neumeister 2015 Steirische Klassik Morillon,Morillon,Neumeister,NaN
13723,54222,NaN,"Almost caramel in color, this wine offers arom...",Babaneuri Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2013 Babaneuri Valley Mtsvane,Mtsvane,Gotsa Family Wines,NaN
14312,913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines,NaN
14313,66524,NaN,"Amber to the eye, this wine features an entici...",Dry Unfiltered Rkatsiteli Mtsvane,88,25.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2015 Dry Unfiltered Rkatsit...,White Blend,Gotsa Family Wines,NaN
15447,36112,NaN,An interesting blend of indigenous Bulgarian a...,Hrumki Melnik 55 Mourvèdre Marselan,89,25.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Orbelus 2012 Hrumki Melnik 55 Mourvèdre Marsel...,Red Blend,Orbelus,NaN
16749,105715,NaN,"Aromas of blackberry, strawberry and chocolate...",Peak,92,50.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Peak Red,Rhône-style Red Blend,Psagot,NaN
16956,49510,NaN,"Aromas of cherry, blueberry and rose petal pre...",NaN,91,34.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2013 Cabernet Sauvignon,Cabernet Sauvignon,Psagot,NaN
17110,113520,NaN,Aromas of crushed stone and graphite lead toas...,Reserve,90,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tannat,Tannat,El Capricho,NaN
17131,90146,NaN,"Aromas of cut grass, lemongrass and honeysuckl...",Nikolaevo Vineyard,89,16.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Nikolaevo Vineyard Gewürztraminer,Gewürztraminer,Ross-idi,NaN
17454,26486,NaN,Aromas of green apple and white flowers prepar...,NaN,87,14.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Teliani Valley 2015 Tsolikouri,Tsolikouri,Teliani Valley,NaN
19303,95176,NaN,Aromatic hints of tomato leaf and pea shoots m...,Klausen,91,38.0,NaN,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Neumeister 2015 Klausen Sauvignon Blanc,Sauvignon Blanc,Neumeister,NaN
20471,26489,NaN,Balanced aromas of green herbs and citrus zest...,Aliwen Reserva,87,12.0,NaN,NaN,NaN,Michael Schachner,@wineschach,Undurraga 2016 Aliwen Reserva Sauvignon Blanc,Sauvignon Blanc,Undurraga,NaN
20865,45402,NaN,Basic cherry aromas turn more earthy and soupy...,Reserva Estate Bottled,85,12.0,NaN,NaN,NaN,Michael Schachner,@wineschach,Chilcas 2015 Reserva Estate Bottled Pinot Noir,Pinot Noir,Chilcas,NaN
25731,120799,NaN,"Cigar box, cedar and red fruit aromas start th...",NaN,90,27.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Ktima Voyatzi 2014 Tsapournakos,Tsapournakos,Ktima Voyatzi,NaN
27960,44674,NaN,Crisp apple freshness almost tips into full ci...,Steirische Klassik,91,25.0,NaN,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Neumeister 2016 Steirische Klassik Grauburgunder,Grauburgunder,Neumeister,NaN
28979,120248,NaN,"Dark ruby in the glass, this wine offers a bou...",M Series,92,36.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2013 M Series Cabernet Franc,Cabernet Franc,Psagot,NaN
29944,18075,NaN,Delicate white flowers and a spin of lemon pee...,Askitikos,90,17.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Askitikos Assyrtiko,Assyrtiko,Tsililis,NaN
31550,129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho,NaN
32942,129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho,NaN
33212,49426,NaN,Enticing aromas of blueberry syrup open this b...,Getika Made With Organic Grapes,88,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Orbelus 2012 Getika Made With Organic Grapes Red,Red Blend,Orbelus,NaN
48029,16000,NaN,"Jumpy, jammy aromas of foxy black fruits are s...",Valle de los Manantiales Vineyard,86,40.0,NaN,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2015 Valle de los Manantiales V...,Tannat,Familia Deicas,NaN
48082,45247,NaN,Just a whiff of citrus shows on the restrained...,Steirische Klassik,89,25.0,NaN,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Neumeister 2016 Steirische Klassik Sauvignon B...,Sauvignon Blanc,Neumeister,NaN
49505,11348,NaN,"Light and fruity, this is a wine that has some...",Partager,82,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager White,White Blend,Barton & Guestier,NaN
52170,85603,NaN,Made from 100% Melnick this garnet-colored win...,Nobile,88,23.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Logodaj 2013 Nobile Melnik,Melnik,Logodaj,NaN
60918,100570,NaN,"Plum, black cherry and anise lead the nose of ...",Theopetra Estate,87,37.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2012 Theopetra Estate Red,Red Blend,Tsililis,NaN
67838,38898,NaN,"Scents of clover, stem, green herb and red cur...",Wismer-Parke Vineyard,89,34.0,NaN,NaN,NaN,Paul Gregutt,@paulgwine,Bachelder 2014 Wismer-Parke Vineyard Pinot Noir,Pinot Noir,Bachelder,NaN
71280,3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier,NaN
73681,97850,NaN,"Streaks of blossom, citrus and pear can be dis...",Gemischter Satz,89,17.0,NaN,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Neumeister 2016 Gemischter Satz White,Austrian white blend,Neumeister,NaN
74123,38240,NaN,Subdued citrus and pear notes on the nose find...,Steirische Klassik,89,24.0,NaN,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Neumeister 2015 Steirische Klassik Grauburgunder,Grauburgunder,Neumeister,NaN
78680,59670,NaN,The heady florality of damask rose is joined b...,Steintal,92,38.0,NaN,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Neumeister 2015 Steintal Roter Traminer,Roter Traminer,Neumeister,NaN
83902,85602,NaN,There's a pleasant fruity richness to this win...,NaN,88,36.0,NaN,NaN,NaN,Lauren Buzzeo,@laurbuzz,Lismore 2014 Chardonnay,Chardonnay,Lismore,NaN
85296,79270,NaN,"This 100% Vranac is garnet in color, with arom...",Premium,86,11.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Stone Castle 2014 Premium Vranac,Vranac,Stone Castle,NaN
86249,49425,NaN,"This blend is comprised of 55% Merlot, 21% Cab...",Getika Made With Organic Grapes,88,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Orbelus 2011 Getika Made With Organic Grapes Red,Red Blend,Orbelus,NaN
86814,44850,NaN,This blend of Gamay and Prokupe has aromas of ...,Amphora,84,6.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Stone Castle 2014 Amphora Red,Red Blend,Stone Castle,NaN
87940,68322,NaN,This Bulgarian Chardonnay is fermented in egg-...,Nikolaevo,89,20.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Nikolaevo Chardonnay,Chardonnay,Ross-idi,NaN
88925,49427,NaN,This dark-garnet wine has aromas of eucalyptus...,Hrumki Syrah Melnik 55 Mourvèdre Marselan,88,19.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Orbelus 2013 Hrumki Syrah Melnik 55 Mourvèdre ...,Red Blend,Orbelus,NaN
88965,119787,NaN,This deep red-violet wine has a nose of blackb...,NaN,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Amiran Vepkhvadze 2014 Otskhanuri Sapere,Otskhanuri Sapere,Amiran Vepkhvadze,NaN
89294,72581,NaN,This dry Furmint from Hungary's Balaton region...,Estate,89,21.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,St. Donat 2014 Estate Furmint,Furmint,St. Donat,NaN
90692,14030,NaN,"This Furmint, grown in marl soils, has aromas ...",Márga,88,25.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,St. Donat 2013 Márga White,White Blend,St. Donat,NaN
94760,27822,NaN,"This is a reasonably rich, concentrated exampl...",NaN,86,19.0,NaN,NaN,NaN,Joe Czerwinski,@JoeCz,Mt. Beautiful 2014 Pinot Gris,Pinot Gris,Mt. Beautiful,NaN
101170,90151,NaN,This medium-straw-colored wine has aromas of c...,NaN,89,25.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Somlói Vándor 2015 Furmint,Furmint,Somlói Vándor,NaN
101397,9509,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis,NaN
102709,9750,NaN,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,Chardonnay,Ross-idi,NaN
102736,98094,NaN,This organically produced wine is comprised of...,Made With Organic Grapes,89,24.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Orbelus 2013 Made With Organic Grapes Melnik,Melnik,Orbelus,NaN
102955,100722,NaN,This Pinot Gris from Switzerland has aromas of...,Domaine de la Treille,89,25.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Les Frères Dutruy 2014 Domaine de la Treille P...,Pinot Gris,Les Frères Dutruy,NaN
106289,124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,90,30.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Les Frères Dutruy 2014 Les Romaines Red,Red Blend,Les Frères Dutruy,NaN
107465,81955,NaN,This white blend is comprised of 50% Chardonna...,Nikolaevo Unison Chardonnay-Gewürtztraminer,89,16.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2014 Nikolaevo Unison Chardonnay-Gewü...,White Blend,Ross-idi,NaN
108223,26485,NaN,"This wine has aromas of black berry, dried red...",NaN,87,13.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Stone Castle 2013 Shiraz,Shiraz,Stone Castle,NaN
108234,44851,NaN,This wine has aromas of honeysuckle and lemon ...,Royal,84,6.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Stone Castle 2015 Royal Riesling,Riesling,Stone Castle,NaN
109346,81957,NaN,This wine is made from grapes grown in the Lak...,Márga,89,18.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,St. Donat 2015 Márga Furmint,Furmint,St. Donat,NaN
110057,129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot,NaN
110668,60678,NaN,"This wine was made for grilled meats, with its...",Dry,86,17.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Ktima Voyatzi 2015 Dry Rosé,Rosé,Ktima Voyatzi,NaN
114901,4243,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking,NaN
117062,16749,NaN,Winemaker: Bartho Eksteen. This wooded Sauvy s...,Cape Winemakers Guild Vloekskoot Wooded,91,NaN,NaN,NaN,NaN,Lauren Buzzeo,@laurbuzz,Bartho Eksteen 2016 Cape Winemakers Guild Vloe...,Sauvignon Blanc,Bartho Eksteen,NaN
117102,57612,NaN,Winemaker: Gordon Newton Johnson. This is such...,Cape Winemakers Guild Windansea,92,NaN,NaN,NaN,NaN,Lauren Buzzeo,@laurbuzz,Newton Johnson 2016 Cape Winemakers Guild Wind...,Pinot Noir,Newton Johnson,NaN

In [138]:
#NaN สามารถแก้ไข เปลี่ยนแปลง ด้วยคำสั่ง เช่น .fillna(“ค่าที่ใส่ไปแทน”) เช่น 
df.region_2.fillna("Unknown")

0                  Unknown
1              North Coast
2         California Other
3                  Unknown
4                  Unknown
                ...
119983             Unknown
119984             Unknown
119985             Unknown
119986    Sierra Foothills
119987             Unknown
Name: region_2, Length: 119988, dtype: object

In [139]:
#หรือการ replace() แทนที่คำที่ต้องการเช่น ต้องการเปลี่ยน twitter handle จาก @kerinokeefe to @kerino 
df.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

0          @vossroger
1             @vboone
2                 NaN
3         @wineschach
4         @wineschach
             ...
119983            NaN
119984            NaN
119985            NaN
119986        @vboone
119987    @AnneInVino
Name: taster_twitter_handle, Length: 119988, dtype: object

In [140]:
df.loc[:,"taster_twitter_handle"]

0          @vossroger
1             @vboone
2                 NaN
3         @wineschach
4         @wineschach
             ...
119983            NaN
119984            NaN
119985            NaN
119986        @vboone
119987    @AnneInVino
Name: taster_twitter_handle, Length: 119988, dtype: object

In [141]:
df.loc[df.taster_twitter_handle == '@kerinokeefe']

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
28,83416,Italy,"100% Cabernet Sauvignon, this opens with aroma...",Basilica del Cortaccio,91,40.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Cafaggio 2010 Basilica del Cortaccio Cabernet ...,Cabernet Sauvignon,Cafaggio,NaN
705,4515,Italy,95 Massolino 2012 Parafada (Barolo). A textb...,Parafada,95,96.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Massolino 2012 Parafada (Barolo),Nebbiolo,Massolino,NaN
819,32753,Italy,A 50-50 blend of Cabernet Sauvignon and Cabern...,Boschivo,90,51.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Leopoldo I di Toscana 2011 Boschivo Red (Toscana),Red Blend,Leopoldo I di Toscana,NaN
822,67300,Italy,A 50-50 blend of Cabernet Sauvignon and Merlot...,Tassinaia,89,40.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Castello del Terriccio 2009 Tassinaia Red (Tos...,Red Blend,Castello del Terriccio,NaN
823,103170,Italy,A 50-50 blend of Cabernet Sauvignon and Merlot...,Balla La Vecchia,88,15.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Fattoria San Felo 2012 Balla La Vecchia Red (T...,Red Blend,Fattoria San Felo,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119735,11237,Italy,"Young and vibrant, this opens with aromas of r...",Bricco Rio Sordo,88,18.0,Piedmont,Barbera d'Alba,NaN,Kerin O’Keefe,@kerinokeefe,Musso 2013 Bricco Rio Sordo (Barbera d'Alba),Barbera,Musso,NaN
119743,67656,Italy,Young but already impeccably balanced and extr...,Bussia,94,90.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Aldo Conterno 2013 Bussia (Barolo),Nebbiolo,Aldo Conterno,NaN
119773,86636,Italy,"Young, juicy and enjoyable, this round fruity ...",Rosso della Motta,89,16.0,Italy Other,NaN,NaN,Kerin O’Keefe,@kerinokeefe,Centovigne 2015 Rosso della Motta Red,Red Blend,Centovigne,NaN
119818,40400,Italy,"Youthful and fresh, this opens with aromas of ...",NaN,87,30.0,Tuscany,Rosso di Montalcino,NaN,Kerin O’Keefe,@kerinokeefe,Castello Romitorio 2014 Rosso di Montalcino,Sangiovese,Castello Romitorio,NaN
119868,26048,Italy,"Zesty and simple, this has fruity aromas of br...",Bocciolo,84,17.0,Piedmont,Colline Novaresi,NaN,Kerin O’Keefe,@kerinokeefe,Ca' Nova 2014 Bocciolo Nebbiolo (Colline Novar...,Nebbiolo,Ca' Nova,NaN

6. Rename and Combining
6.1 Renaming
	การแก้ไขชื่อของคอลัมน์ด้วยคำสั่ง rename() เช่น ต้องการเปลี่ยน points เป็น score

In [142]:
df.rename(columns={'points': 'score'})

,id,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [143]:
#สามารถเปลี่ยนชื่อ index ได้ เช่น เปลี่ยน index 0 เป็น firstEntry และ 1 เป็น secondEntry
df.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
firstEntry,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
secondEntry,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [144]:
df.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

fields,id,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,dupe?
wines,,,,,,,,,,,,,,,
0,94355,Austria,"""Chremisa,"" the ancient name of Krems, is comm...",Edition Chremisa Sandgrube 13,85,24.0,Niederösterreich,NaN,NaN,Roger Voss,@vossroger,Winzer Krems 2011 Edition Chremisa Sandgrube 1...,Grüner Veltliner,Winzer Krems,NaN
1,126883,US,$10 for this very drinkable Cab? That's crazy....,NaN,87,10.0,California,North Coast,North Coast,Virginie Boone,@vboone,Line 39 2009 Cabernet Sauvignon (North Coast),Cabernet Sauvignon,Line 39,NaN
2,119493,US,$14 is a pretty good price for a Chardonnay th...,Whiplash,86,14.0,California,California,California Other,NaN,NaN,Jamieson Ranch 2011 Whiplash Chardonnay (Calif...,Chardonnay,Jamieson Ranch,NaN
3,126909,Spain,"). Earth, cola and leather aromas are good, ho...",Finca Resalso,86,15.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Finca Resalso (Ribera del Du...,Tinto Fino,Emilio Moro,NaN
4,119752,Spain,). Light and lemony on the nose. The palate ha...,NaN,87,17.0,Galicia,Rías Baixas,NaN,Michael Schachner,@wineschach,La Caña 2010 Albariño (Rías Baixas),Albariño,La Caña,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119983,80210,Italy,Zonchera is Ceretto's more affordable base Bar...,Zonchera,90,48.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2004 Zonchera (Barolo),Nebbiolo,Ceretto,NaN
119984,76487,Italy,Zonin's 2006 Amarone opens with very ripe arom...,NaN,88,70.0,Veneto,Amarone della Valpolicella,NaN,NaN,NaN,Zonin 2006 Amarone della Valpolicella,"Corvina, Rondinella, Molinara",Zonin,NaN
119985,86953,Italy,Zorzettig's precious Picolit dessert wine deli...,NaN,90,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,NaN,NaN,Zorzettig 2006 Picolit (Colli Orientali del Fr...,Picolit,Zorzettig,NaN
119986,18824,US,Zucca has made a fragrant and floral Sangioves...,Sangiovese Rosato,87,18.0,California,Amador County,Sierra Foothills,Virginie Boone,@vboone,Zucca 2010 Sangiovese Rosato Rosé (Amador County),Rosé,Zucca,NaN
119987,88999,Austria,Zweigelt can do easy-drinking styles but in th...,Heideboden,90,26.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nittnaus Hans und Christine 2013 Heideboden Zw...,Zweigelt,Nittnaus Hans und Christine,NaN

In [ ]:
# #Export
# df.to_csv("new_superwine.csv")